### ISSUE TITLE
OpenSuSE hostkey management

### ISSUE THREAD

**Issue by lazyfrosch** [ghoneycutt/puppet-module-ssh#103]
Okay, so I know a bit more about the problem on OpenSuSE: The Initscript, or the Systemd integration only generates keys, when no keys are generated.

This happens when no sshd is present prior to the Puppet run and the sshd_config of the module gets written before starting the service or running the key initialization.

```
if ! grep -q '^[[:space:]]*HostKey[[:space:]]' /etc/ssh/sshd_config; then
```

Also see PR #102

**Comment by ghoneycutt** [comment]
Cleaning out old issues. If you are still interested in this, please re-open.
