### ISSUE TITLE
Support for validate_cmd

### ISSUE THREAD

**Issue by Raskil** [ghoneycutt/puppet-module-ssh#122]
Hi,

Would it be possible to add support for the file types validate_cmd to make use of opensshd -t -f command flags for testing the config file before restarting the service?

This way you make sure that you don't put a config file in place that breaks sshd.

Regards

Raskil

**Comment by ghoneycutt** [comment]
Great idea. Could you please send a pull request?

**Comment by Raskil** [comment]
Hi,

I've send a pull request. Please tell me if anything is missing or unclear. I've never worked with github before.

Regards

Raskil

**Comment by lazyfrosch** [comment]
Question: Wouldn't it be better to verify the config on the target system?

File[sshd_config.tmp] -> Exec[ssh_config_verify] -> File[sshd_config]

**Comment by Raskil** [comment]
Well, the validate_cmd command will be executed on the target system for Puppet 3.5 and later.
Maybe you change would be nicer than using the stdlib validate_cmd on versions prior to 3.5.

**Comment by lazyfrosch** [comment]
Ah, you are using validate_cmd of the file type, I see

**Comment by ghoneycutt** [comment]
Cleaning out old issues. If you are still interested in this, please re-open with a pull request. BTW: the test would need to check for which version of ssh is being used as this module supports other implementations besides OpenSSH.
