### ISSUE TITLE
sshd_config_match host configuration

### ISSUE THREAD

**Issue by apazga** [ghoneycutt/puppet-module-ssh#128]
**Versions used:**
- CentOS 7.0 (3.10.0-123.20.1.el7.x86_64)
- Puppet 4.2.1
- r10k 2.0.3
- Git 1.8.3.1
- module ghoneycutt/ssh 3.30.0

The following configuration (via Hiera) doesn't work:
```yaml
ssh::sshd_config_match:
  'Host mymachine.mydomain.com':
    'PermitRootLogin yes'
```

Other configuration parameters I use via hiera work, e.g.:
```yaml
ssh::sshd_config_syslog_facility: 'AUTHPRIV'
ssh::sshd_config_challenge_resp_auth: 'no'
ssh::permit_root_login: 'no'
```

**Error output** when *sshd_config_match* is included:
```log
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Failed to parse template ssh/sshd_config.erb:
  Filepath: /etc/puppetlabs/code/environments/public/modules_external/ssh/templates/sshd_config.erb
  Line: 222
  Detail: undefined method `sort' for "PermitRootLogin yes":String
 at /etc/puppetlabs/code/environments/public/modules_external/ssh/manifests/init.pp:661:16 on node puppet-test.mydomain.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Am I missing something?
Thanks in advance.

**Comment by nalyanyam** [comment]
@apazga 

Please try the following configuration in hiera:

ssh::sshd_config_match:
   'Host mymachine.mydomain.com':
      - 'PermitRootLogin yes'

**Comment by nalyanyam** [comment]
The order is scrambled up - but the idea is to specify the values as an array. More information is in README

**Comment by apazga** [comment]
Thank you very much @nalyanyam. I understand it know.

Working one (white spaces and hyphen are critical):
```yaml
ssh::sshd_config_match:
  'Host mymachine.mydomain.com':
    - 'PermitRootLogin yes'
```

**Comment by ghoneycutt** [comment]
Let's leave this open until we update the README to be explicit that the options must be an array. Or we can change template to detect if the class is an array or a string and only `.each` on the array.

**Comment by ghoneycutt** [comment]
The readme is now explicit.

**Comment by baragoon** [comment]
Hi!
I'm new to puppet and now trying to set sshd_config_match and i't unclear for me how to add a match entry with your module. Please, can you give me an advise, for example to add
"Match User backup
 PubkeyAuthentication yes" with your module.
Thank you and sorry for bad English.

**Comment by ghoneycutt** [comment]
Try this

```yaml
ssh::sshd_config_match:
  'User backup':
    - 'PubkeyAuthentication yes'
```
