### ISSUE TITLE
sshd_config allows multiple instances in config, but sshd_config_port is single valued 

### ISSUE THREAD

**Issue by sbroddy** [ghoneycutt/puppet-module-ssh#130]
Hello, 

In our environment, we run sshd on multiple ports.  The sshd config allows for this (from the manpage):

      Port    Specifies the port number that sshd(8) listens on.  
      The default is 22.  Multiple options of this type are permitted.  
      See also ListenAddress.

How hard would it be to modify things so that sshd_config_port would accept an array?  Such as (in hiera):

ssh::sshd_config_port:
  - '22'
  - '1111'

I'm just getting started with hiera, so there may be another easier way to accomplish what I need, but at present it looks to me like this module will not accept multiple values for this configuration option.

Thank you for providing some great modules!

**Comment by bschonec** [comment]
I'm thinking the same thing.  I can modify the code but I am *not* qualified to write spec tests.   I have no idea how to do that.

**Comment by ghoneycutt** [comment]
I can help with the spec tests. Can you please send a PR for accepting an array of ports? Be sure to also update the README when doing so.

**Comment by ghoneycutt** [comment]
Functionality added in v3.40.0
