### ISSUE TITLE
puppet stdlib function 'type3x' has been deprecated

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-ssh#138]
Replace?

**Comment by Phil-Friderici** [comment]
I hope that wil not happen before stdlib v6

The manual says:
> This function will be removed when Puppet 3 support is dropped and the new type system can be used.

https://github.com/puppetlabs/puppetlabs-stdlib#type3x

Puppet v3 should still be supported at least in stdlib v5
https://github.com/puppetlabs/puppetlabs-stdlib#version-compatibility

But for the interested one, you could use ```is_bool()```, ```is_string()``` and friends.

**Comment by ghoneycutt** [comment]
Agreed it should be replaced as Phil mentioned though this is certainly not a priority. I'd be happy to merge it though! :)
