### ISSUE TITLE
RHEL 6 - AuthorizedKeysCommandRunAs

### ISSUE THREAD

**Issue by rdrgmnzs** [ghoneycutt/puppet-module-ssh#150]
RHEL 6 / CentOS 6 does not support AuthorizedKeysCommandUser, it uses AuthorizedKeysCommandRunAs instead.

I'm happy to write a pull request to fix this, I'm just not sure if you'd rather have this as a if and else if, inside the ERB or if you rather have something inside a pp file.

**Comment by ghoneycutt** [comment]
Do you know if this is specific to EL6 or to all versions of OpenSSH >= X ?

If the configuration parameters are equivalent and just named differently for different versions, then a conditional in the template is a good call as you suggested.

Thanks!

**Comment by brdude** [comment]
I don't know if it is EL6 or to all versions of OpenSSH >= X ?, I'll do some testing in the upcoming days and let you know.

Yep the configuration parameters are equivalent and just named differently.

**Comment by ghoneycutt** [comment]
More information is needed to address this. I am unsure as to why the commands are different. Did this happen in a version of OpenSSH?

**Comment by aholen** [comment]
This changed in OpenSSH 6.2 (or possibly in openssh 6.1p1):
https://bugzilla.redhat.com/show_bug.cgi?id=953534

6.2 or higher should use: AuthorizedKeysCommandUser
<6.2 should use: AuthorizedKeysCommandRunAs

**Comment by ghoneycutt** [comment]
Thanks @aholen 

We should be able to use a conditional on the `ssh_version_numeric` fact to solve this.

**Comment by cjedwa** [comment]
@ghoneycutt 

This seems like an actual issue. Can we get this re-opened?

**Comment by Phil-Friderici** [comment]
In v4 `AuthorizedKeysCommandUser` is nativly supported. To use `AuthorizedKeysCommandRunAs` you can use the `$custom` parameter.
Please re-open if this doesn't fit your use case.
