### ISSUE TITLE
UseRoaming in ssh_config is not a valid option for Suse 11.2 and Red Hat 5 (fixed on EL5)

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-ssh#155]
Example:

UseRoaming=no is in /etc/ssh/ssh_config:

[root@demo64 ~]$ sudo /bin/bash
[root@demo64 ~]# ssh example.com
/etc/ssh/ssh_config: line 57: Bad configuration option: UseRoaming
/etc/ssh/ssh_config: terminating, 1 bad configuration options
# Delete UseRoaming line:

[root@demo64 ~]# sed -i '/UseRoam/d' /etc/ssh/ssh_config 
[root@demo64 ~]# ssh example.com
<successful connection attempt>

**Comment by dfairhurst** [comment]
I have the same issue, and there is no way to remove the parameter from the config through Hiera, as the default value is 'USE_DEFAULTS' and you cannot set an 'undef' value through Hiera

**Comment by ghoneycutt** [comment]
The fixture for EL5 does not contain UseRoaming, so that should be fixed.

The fixture for Suse11 does contain UseRoaming and is still an issue.

@dfairhurst could you provide an unmodified ssh_config and sshd_config from a default install of Suse 11? We can use that as a fixture for testing.

**Comment by Phil-Friderici** [comment]
`UseRoaming` has been removed entirely in v4.
