### ISSUE TITLE
Warnings if storeconfigs not set

### ISSUE THREAD

**Issue by siliconalchemy** [ghoneycutt/puppet-module-ssh#159]
Can this be suppressed?

```
Warning: You cannot collect without storeconfigs being set on line 753 in file /srv/puppet/manifests/environments/dev/puppet-modules/ssh/manifests/init.pp
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 767 in file /srv/puppet/manifests/environments/dev/puppet-modules/ssh/manifests/init.pp
```

Using puppet apply with no -v or -d.

Calling with:
```
    class { "::ssh": 
        ssh_key_import  => false,
    }
```

**Comment by ssm** [comment]
To suppress this warning from the puppet language parser, you need to move the export and collect to a separate manifest, and only include that manifest based on a parameter value. 

I used that in [ssm-munin commit 78fa8774](https://github.com/ssm/ssm-munin/commit/78fa8774a7f932261a01775832f159a5139b486c#diff-496e479926ea49925dab22299df86ebb) to address ssm/ssm-munin#30, which is the exact same issue.

**Comment by ghoneycutt** [comment]
It is just a warning about storeconfigs, in case you were expecting them to work. It is OK and does not need to be suppressed as it is there by design.
