### ISSUE TITLE
Proper usage of keys parameter

### ISSUE THREAD

**Issue by bortek** [ghoneycutt/puppet-module-ssh#160]
Hi

I am trying to make puppet-module-ssh to distribute user's public key to the servers so that a user can authenticate using keys instead of a password. 

There is a parameter called Keys which is described as 

keys
Hash of keys for user's ~/.ssh/authorized_keys
Default: undefined

Then at the bottom of the doc page is says: 
Manage user's ssh_authorized_keys
This works by passing the ssh::keys hash to the ssh_authorized_keys type with create_resources(). Because of this, you may specify any valid parameter for ssh_authorized_key.
Then comes the usage example.

So what I have done is set keys parameter of puppet-module-ssh to this exact value

ssh::keys:
  marry123:
    ensure: present
    user: marry123
    type: rsa
    key: ''AAAAREAL_KEY_REMOVED=='

But this does not seem to work. There is no key created in users home directory under .ssh.

I am using the parameter correctly?

**Comment by ghoneycutt** [comment]
You can quote things using three backticks. If you have exactly what is above, it is not valid yaml.

**Comment by ghoneycutt** [comment]
You probably also want `ssh::hiera_merge: true` so that it does a merge lookup of Hiera instead of stopping at the first match.

**Comment by bortek** [comment]
Ooops I think I had a too many quot marks.

It looks like this now. My delimts look right, but they are not showing properly here in the comment.

ssh::keys:
  marry123:
    ensure: present
    user: marry123
    type: rsa
    key: 'AAAAREMOVED=='


To be more specific, I am using this module in RH Satelliet 6.1. In the Smart class parameters I override some of the default parameters to set my own ones and they work just fine. But not this one.

**Comment by bortek** [comment]
I am not using hiera and even if I enable it it does not work. 

Now I enabled debug on puppet agent and found this in the puppet logs.

"ssh::keys:\r\n  marry123:\r\n    ensure: present\r\n    user: marry123\r\n    type: rsa\r\n    key: 'AAAAB3REMOVED=='" is not a Hash.  It looks to be a String 

Can we really pass any valid parameters that ssh_authorized_key type supports using ssh::key ? It looks like it expects only hash of a key.

**Comment by ghoneycutt** [comment]
keys must be a hash. You can pass any valid ssh_authorized_key params as part of that hash. What you are showing me should work though it seems that whatever backend you are using is returning it as a string instead of a hash. I would like there and see how to represent hashes.

**Comment by bortek** [comment]
I won't more time on this as it wont work anyway since ssh_authorized_key is putting keys in /home/USER/.ssh directory. While I have explicitly moved my users keys to a different directory (via sshd_config) to disallow them managing it.

I will write my own puppet module instead that will do the job. 

Thanks for your input @ghoneycutt !

Closing this issue.

**Comment by ghoneycutt** [comment]
You can specify the target.

https://docs.puppet.com/puppet/3.8/reference/type.html#ssh_authorized_key-attribute-target

**Comment by bortek** [comment]
I know. But that area is owed by root while puppet is trying to write a fule as a user owning the key (marry123)  and gets permission denied, since the area is only root writable.
