### ISSUE TITLE
Support of Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by hoene** [ghoneycutt/puppet-module-ssh#183]
currently it fails because of

"Error: /Stage[main]/Ssh/Service[sshd_service]: Could not evaluate: Execution of '/sbin/status ssh' returned 1: status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused"

**Comment by choene** [comment]
check to https://bugs.launchpad.net/ubuntu/+source/puppet/+bug/1457957, too.

**Comment by lazyfrosch** [comment]
This is a problem with Puppet 3.x (and I think some early 4.x versions) to choose the wrong default provider for services.

You should probably set the default provider explicitly somewhere with `site.pp` of your environment

**Comment by ghoneycutt** [comment]
We can modify the code to set the provider if needed. What is the correct provider for SSH on Ubuntu 16.04 LTS? From the link above I got the idea that there could be three different ones and you can mix and match between your services, so I'm not clear what the provider should be set to specifically for sshd.

**Comment by lazyfrosch** [comment]
Ubuntu 16.04 is using systemd, earlier versions upstart.

Users can do this at top-level by:

```puppet
Service {
  provider => 'systemd',
}
```

Defaults are good in current Puppet:
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/service/upstart.rb#L21

But 3.x is wrong:
https://github.com/puppetlabs/puppet/blob/3.8.7/lib/puppet/provider/service/upstart.rb#L15

**Comment by ghoneycutt** [comment]
@choene @lazyfrosch would you be interested in adding support for Ubuntu 16.04 LTS? It would require adding a parameter, service_provider, that defaults to undef on the other platforms and 'systemd' on Ubuntu 16.04. Besides that, it would need an entry added to the osfamily matrix at the top of spec/classes/init_spec.rb

**Comment by lazyfrosch** [comment]
I don't think it would make sense to introduce such a parameter:

1. It's a Puppet bug / out of date OS info
2. It's not a module specific problem, should cause problems with all `service`
3. The proper way to set such defaults should be `site.pp`

**Comment by ghoneycutt** [comment]
Setting a provider is not out of the ordinary, as this is often done with package resources. I would like to support Ubuntu 16.04 LTS on Puppet v3, so if setting the provider by default gets us there, then that's OK with me.

It also appears that with Ubuntu 16.04 LTS you can decide between three different ways of starting services and can tailor it to each service. While this seems unwise, it is what the distro does, so being able to set it per service (as opposed to the site.pp) seems OK as well.

**Comment by ikkaro** [comment]
I've tried this in service.pp, but it fails:

```
  if $::lsbdistcodename == "Xenial"
  {
      service { $ssh::params::service_name:
        ensure     => $ssh::server::service::ensure,
        hasstatus  => true,
        hasrestart => true,
        provider   => 'systemd',
        enable     => $ssh::server::service::enable,
        require    => Class['ssh::server::config'],
      }
  }
  else {
      service { $ssh::params::service_name:
        ensure     => $ssh::server::service::ensure,
        hasstatus  => true,
        hasrestart => true,
        enable     => $ssh::server::service::enable,
        require    => Class['ssh::server::config'],
      }
  }
```
Someone solved this issue in puppet 3?

**Comment by Phil-Friderici** [comment]
Closing as support for Ubuntu 16.04 have been deprecated and removed.
