### ISSUE TITLE
Ubuntu 16.04 new server keys generated?

### ISSUE THREAD

**Issue by cliff-wakefield** [ghoneycutt/puppet-module-ssh#187]
Hi,

Just started to use this module on Ubuntu 16.04 and it seems to regenerate the SSH server keys?

Is this normal behaviour?

Can't see anything in the module to request that this isn't done?

**Comment by cliff-wakefield** [comment]
Sorry it's not changing the keys its removing /etc/ssh/ssh_host_ecdsa_key which appears to be the default key offered up by Ubuntu 16.04 server to a Ubuntu 16.04 client.

Not sure why /etc/ssh/ssh_host_ecdsa_key is disabled?

**Comment by ghoneycutt** [comment]
If HostKey in sshd_config changes and sshd restarts, it would generate keys in the new location. Would be very happy to add Ubuntu 16.04 LTS support with your help.

Could you please provide stock copies of /etc/ssh_config and /etc/sshd_config as they are in a default install, the output of `ssh -V` and `facter`.

**Comment by ghoneycutt** [comment]
Putting them in gists would be greatly appreciated!

https://gist.github.com/

**Comment by cliff-wakefield** [comment]
Worked around it for the moment doing

ssh::sshd_config_hostkey:
 - '/etc/ssh/ssh_host_rsa_key'
 - '/etc/ssh/ssh_host_ecdsa_key'

**Comment by cliff-wakefield** [comment]
This is on a clean Ubuntu 16.04 EC2 instance un-patched.

# ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu1, OpenSSL 1.0.2g-fips  1 Mar 2016

puppet agent details https://gist.github.com/cliff-wakefield/42fb93b8cf7b53c2c55b6ae9d84986c1
Facter output https://gist.github.com/cliff-wakefield/b232ef51799908a0264eb7e95af09092
ssh_config https://gist.github.com/cliff-wakefield/a7b054f7bd6a5fe56c9fdfa2903b8368
sshd_config https://gist.github.com/cliff-wakefield/194418a61586ad3f137e6fa52fd7af46

**Comment by ghoneycutt** [comment]
Ubuntu 16.04 LTS support released in v3.45.0

Thanks a ton for your help!
