### ISSUE TITLE
Allow use of an .erb template file for sshd_banner_content

### ISSUE THREAD

**Issue by hiltonaipfw** [ghoneycutt/puppet-module-ssh#190]
It would be great if you could add in the ability to use a template file for the contents of the sshd banner file. Our banner is 10 lines long and it gets really ugly to edit it and get the newlines and spacing right. Using a template file would take care of that problem.

**Comment by ghoneycutt** [comment]
I would put it in Hiera first. Next best solution would be to use a profile that wraps around ssh and include your profile instead of the ssh class directly.

ie:

```puppet
class profile::ssh {
  $banner = template('profile/ssh/banner.erb'),

  class { 'ssh':
    sshd_banner_content => $banner,
  }
}
```

**Comment by ghoneycutt** [comment]
Do one of these options work for you?

**Comment by hiltonaipfw** [comment]
It does - I configured it to work with the wrapper this morning and it is working great. Thanks for the follow-up!
