### ISSUE TITLE
No KexAlgorithms Support

### ISSUE THREAD

**Issue by flix444** [ghoneycutt/puppet-module-ssh#192]
Hello,
there is no array for  KexAlgorithms configuration. 

https://wiki.mozilla.org/Security/Guidelines/OpenSSH

kr Felix

**Comment by ghoneycutt** [comment]
I would happy to receive a pull request that adds support for that option.

**Comment by flix444** [comment]
Oh, someone did already a pull request for KexAlgorithms. 
https://github.com/ghoneycutt/puppet-module-ssh/pull/146

**Comment by Asteao** [comment]
Issues has been resolved with #195
