### ISSUE TITLE
References unknown variable ::ssh_version

### ISSUE THREAD

**Issue by chrisowensboston** [ghoneycutt/puppet-module-ssh#194]
Line 263 of init.pp references unknown variable ::ssh_version

**Comment by ghoneycutt** [comment]
ssh_version is a fact included with this module. Are you experiencing a problem using the module? If so, please include more information such as how you are using the module and what is happening that is not expected.

**Comment by ghoneycutt** [comment]
Please re-open if this is still an issue with the requested information. Thank you for reporting!
