### ISSUE TITLE
Something wrong with known hosts

### ISSUE THREAD

**Issue by ksemaev** [ghoneycutt/puppet-module-ssh#205]
Maybe I'm getting something wrong, but default settings of module get every host's name plus common pulic key and puts on every node in /etc/ssh/ssh_known_hosts

So when one new node is added to puppet, his name will get to known hosts on every other puppet nodes in /etc/ssh/ssh_known_hosts

Why is that hapenning?)

**Comment by ksemaev** [comment]
So I get that puppetserver imports all keys (for some wierd reason), but why he adds it to all managed nodes to known hosts? I don't need this functionality, and doubt that anybody needs it as default setting

**Comment by ghoneycutt** [comment]
If you do not want to import keys, then set `ssh_key_import` to `false`.

https://github.com/ghoneycutt/puppet-module-ssh#ssh_key_import

Its purpose is to allow you to enable StrictHostKeyChecking for added security. It also ensures you do not have to type 'yes' when ssh'ing to a new host for the first time. You are probably right that it should not be the default.

**Comment by ksemaev** [comment]
yes, I get it - but new keys not only appear on server, but they are also added to each managed node. So it is good - if I want to have this keys on master. But why they also get on every node? For example: I add one new system as puppet agent, it syncs, and after that all of my managed 1000 nodes are getting this new ssh key at their next sync.
Can I disable this last part?)

**Comment by ghoneycutt** [comment]
https://docs.puppet.com/puppet/latest/lang_exported.html

The key for each host is being exported and all of them are being imported. It doesn't really make sense to me to only import on your puppet master, though if that's your goal you could do disable the import for all systems as explained above and then have a profile for your puppet master that does the import with the following code.

```puppet
Sshkey <<||>>
```
