### ISSUE TITLE
AcceptEnv parameters static, not configurable 

### ISSUE THREAD

**Issue by systeemkabouter** [ghoneycutt/puppet-module-ssh#207]
The AcceptEnv currently is a boolean switch. I need to pass a custom set of variables that should be preserved. I don't think the module currently allow for that. 

Willing to come up with a PR, but wanted to discuss this issue first.

**Comment by SimonHoenscheid** [comment]
I ran into the same today. Will file a PR soon.

**Comment by Phil-Friderici** [comment]
Fixed in v4.
