### ISSUE TITLE
Solaris 10 config options issue

### ISSUE THREAD

**Issue by redno2** [ghoneycutt/puppet-module-ssh#208]
Failed on Solaris 10, the options TCPKeepAlive and PermitTunnel doesn't exist..

-bash-3.2# cat /etc/release     
                    Oracle Solaris 10 1/13 s10x_u11wos_24a X86
  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.
                            Assembled 17 January 2013

/opt/puppetlabs/bin/puppet --version    
4.3.2

[ Jan 20 10:47:40 Executing start method ("/lib/svc/method/sshd start") ]
/etc/ssh/sshd_config: line 105: Bad configuration option: TCPKeepAlive
/etc/ssh/sshd_config: line 119: Bad configuration option: PermitTunnel
/etc/ssh/sshd_config: terminating, 2 bad configuration options

**Comment by Phil-Friderici** [comment]
+1 having seen the same issue here. Hope I can find time soon to create & propose a fix.

**Comment by Phil-Friderici** [comment]
v3.43.0 is the last version that does not break on Solaris.

**Comment by Phil-Friderici** [comment]
Thanks to @nalyanyam I got a list of Solaris incompatible parameters:

KerberosOrLocalPasswd - not valid
KerberosTicketCleanup - not valid
KerberosGetAFSToken - not valid
TCPKeepAlive -  not valid
ShowPatchLevel - not valid
MaxSessions - not valid
PermitTunnel - not valid

We should find a way to exclude them from Solaris SSHd for the future.
Two way come into my mind here:
- Solaris specific template without the incompatible parameters
- enable the template to print out lines only if the value is not undef and set OS default accordingly

I would prefer last one as it could help in other situattions too.
@ghoneycutt What do you think ?

**Comment by ghoneycutt** [comment]
I'd like to keep one template and configure it so that if a setting is undef it will not show up.

**Comment by ghoneycutt** [comment]
Perhaps we could tap into E's Jenkins service and get a few Solaris VM's. We could build a job that runs the code from a PR and tests it on a Solaris VM with serverspec and then reverts the VM. This would give us an automated way to ensure Solaris is good.

**Comment by Phil-Friderici** [comment]
@ghoneycutt Having some Jenkins magic to verify compatibility would be awesome. Getting an environment for full automated testing is on my wish list. Just I believe this will take some time before I can start working into that direction.

**Comment by Phil-Friderici** [comment]
But I will start working on an suggestion for the template.

One detail come into my mind; in Hiera it is not possible to override a value to become undef once it is set. Therefore I think it would be good to have an alternative 'stop word' beside undef.

**Comment by nalyanyam** [comment]
@Phil-Friderici These settings in ssh_config are also not valid on Solaris

AddressFamily
Tunnel
TunnelDevice
PermitLocalCommand
HashKnownHosts

**Comment by Phil-Friderici** [comment]
There is my suggestion how to fix the incompatible parameters on Solaris: https://github.com/ghoneycutt/puppet-module-ssh/pull/213

@ghoneycutt if this goes into the right direction, I'll add the same for the other parameters.

**Comment by Phil-Friderici** [comment]
Hiera does not allow reseting a specified value back to undef again. As workaround I have added the value 'unset' which does that.

@nalyanyam To address the Solaris incompatible parameters I have take care that each changeable parameter can take 'unset' as value. This will not add the parameter to the configuration files anymore.

I was only able to do that for the already parameterized parameters. Don't know how to progress with the other incompatible parameters.

**ssh_config**
AddressFamily
Tunnel
TunnelDevice
PermitLocalCommand

**sshd_config**
KerberosOrLocalPasswd
KerberosTicketCleanup
KerberosGetAFSToken
ShowPatchLevel

**Comment by ghoneycutt** [comment]
Thanks everyone! Released in v3.49.1
