### ISSUE TITLE
When created keys for users in authorized_keys ensure .ssh and authorized_keys exist and proper permissions

### ISSUE THREAD

**Issue by benkevan** [ghoneycutt/puppet-module-ssh#214]
Default /etc/skel in CentOS 7 doesn't include ~/.ssh, therefore, this has to be done manually prior to adding keys for the specific user. 

Recommending that the module confirms that ~/.ssh directory exists and is 600 and ~/.ssh/authorized_key exists and is 600.

**Comment by ghoneycutt** [comment]
I think this would conflict with https://github.com/ghoneycutt/puppet-module-common#manage_dotssh

**Comment by benkevan** [comment]
The manage_dotssh assumes that puppet is creating the account. In my case with SSSD accounts aren't handled by puppet but the contents could/should be managed by puppet. 

Creating a user without .ssh isn't necessarily an evil, I personally feel that .ssh should be managed by an ssh module and not by a user creation module (for what my .02 is worth).

**Comment by ghoneycutt** [comment]
This module uses the ssh_authorized_key type and it appears that the provider will create the directory for you.

**Comment by benkevan** [comment]
When testing it didn't create the .ssh directory nor the authorized_key.. I'll dig into it a bit more soon hopefully.
