### ISSUE TITLE
default_sshd_config_hostkey should be enhanced for EL7

### ISSUE THREAD

**Issue by TJM** [ghoneycutt/puppet-module-ssh#220]
I got this diff while running this module:

```
 # HostKey for protocol version 1
 #HostKey /etc/ssh/ssh_host_key
 # HostKeys for protocol version 2
-HostKey /etc/ssh/ssh_host_rsa_key
+#HostKey /etc/ssh/ssh_host_rsa_key
 #HostKey /etc/ssh/ssh_host_dsa_key
-HostKey /etc/ssh/ssh_host_ecdsa_key
-HostKey /etc/ssh/ssh_host_ed25519_key
+HostKey /etc/ssh/ssh_host_rsa_key
```

It would appear that `default_sshd_config_hostkey` does not have a "case" to handle EL6 vs EL7. EL7 should default correctly to have the newer ecdsa and ed25519 keys. Of course there is an easy workaround of specifying `sshd_config_hostkey` in hiera like so:

```
ssh::sshd_config_hostkey:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
```

~tommy

**Comment by TJM** [comment]
In addition, we noticed this:

```
-UsePrivilegeSeparation sandbox		# Default for new installations.
+#UsePrivilegeSeparation yes
```

and

```
-Subsystem sftp	/usr/libexec/openssh/sftp-server
+Subsystem sftp /usr/libexec/openssh/sftp-server
```

**Comment by Phil-Friderici** [comment]
Fixed in v4. There you can specify `HostKey` and `Subsystem `to fit your needs. `UsePrivilegeSeparation` can be set using `$custom`.
