### ISSUE TITLE
Replace validate_* calls with Puppet4 Data Types

### ISSUE THREAD

**Issue by dhollinger** [ghoneycutt/puppet-module-ssh#222]
The Puppetlabs-stdlib `validate-*` methods have been deprecated and could be removed at any moment. These methods have been replaced with Puppet 4 Data Types. 

Using Puppet 4 Data types would significantly clean up the module code, but would require a full drop of Puppet 3 support. That said Puppet, Inc ended support for Puppet 3.x on Jan 1st, 2017

https://docs.puppet.com/puppet/4.10/lang_data_type.html

**Comment by ghoneycutt** [comment]
I've got this on my roadmap to transition all of the modules to the next major version and drop support for Puppet 3.

**Comment by Phil-Friderici** [comment]
Fixed in v4.
