### ISSUE TITLE
Warning '6' coerced to 6

### ISSUE THREAD

**Issue by rgarrigue** [ghoneycutt/puppet-module-ssh#231]
Hi

Since I was around, just a little warning popping up on my test env

    ==> test.vagrant.local: Warning: The string '6' was automatically coerced to the numerical value 6 at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/init.pp:283:3

Cheers,

**Comment by ghoneycutt** [comment]
Thanks for reporting. When moving to Puppet v4 only and dropping support for v3, we should use integers instead of strings where appropriate.

**Comment by fnoop** [comment]
Yes, these warnings have popped up on every run since an upgrade from puppet 4.10.1 to 4.10.4:
```
Warning: The string '7' was automatically coerced to the numerical value 7 at /srv/maverick/software/maverick/manifests/puppet-modules/ssh/manifests/init.pp:283:32
Warning: The string '2' was automatically coerced to the numerical value 2 at /srv/maverick/software/maverick/manifests/puppet-modules/ssh/manifests/init.pp:284:32
```

**Comment by baurmatt** [comment]
@ghoneycutt When are you planning to remove the support of Puppet 3? Its EOL for almost a year now ;)

**Comment by darkfeline** [comment]
Ubuntu Trusty is EOL in 2019, and it still ships Puppet 3.4.3.

I hate having to support/maintain old software as much as any other developer, just keep in mind that supporting old versions is much appreciated for the poor people who have no choice but to use old versions.

**Comment by baurmatt** [comment]
That's definitely not a good excuse. You can easily use the stable packages provided by http://apt.puppetlabs.com/. If not, I could argue that CentOS 7 also includes Puppet 3 and is supported until 2024. I pretty sure we shouldn't wait that long ;)

**Comment by ghoneycutt** [comment]
Currently working through upgrading my most used modules to support Puppet 5 and drop support for Puppet 3. SSH is next after pam and yum.

I intend to continue to support old OS platforms, just not old puppet versions. @darkfeline You can run newer puppet versions on your old platforms.

**Comment by darkfeline** [comment]
If all organizations/managers listened to reason, the world would be a very different place.  Packages shipped in the official repos is very different from installing from third party sources from a policy perspective.  I am not demanding that Puppet 3 be supported, I am just saying why some users may want it. Anecdotally, I think more orgs run LTS Ubuntu than CentOS.

**Comment by ghoneycutt** [comment]
@darkfeline When we drop support for Puppet3 it will be a major version change. While I will not actively support Puppet 3, I can leave a puppet3 branch in this repo and will merge pull requests to that branch if the community wants to send PR's and keep it alive.

**Comment by linuxphone** [comment]
Was this issue ever fixed, I still see the WARN in my puppet runs. Please advise

**Comment by Phil-Friderici** [comment]
Fixed in v4.
