### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by rgarrigue** [ghoneycutt/puppet-module-ssh#232]
And another warning (I'm running latest stdlib)

    ==> test.vagrant.local: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/ssh/manifests/init.pp", 333]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/ssh.pp", 9]
==> test.vagrant.local:    (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')

**Comment by ghoneycutt** [comment]
We need to drop support for Puppet 3 and switch to 4 only syntax.

**Comment by Phil-Friderici** [comment]
Fixed in v4.
