### ISSUE TITLE
support multiple sshd daemon

### ISSUE THREAD

**Issue by khaefeli** [ghoneycutt/puppet-module-ssh#233]
Hi,

first: thank you for this nice module! 
we're using it on many nodes.

is it planed to support multiple ssh daemons in future?
I would like to configure >=2 ssh daemons on one node for ssh fileexchange (including chrooted directories)

cheers,
Kevin

**Comment by ghoneycutt** [comment]
I don't quite follow you. Can you give an example of how the configs would change?

**Comment by khaefeli** [comment]
we have multiple ` ssh_config_xy`  in our ` /etc/ssh` 

running process:
` /usr/sbin/sshd -f /etc/ssh/sshd_config_xy-o PidFile=/var/run/sshd-xy.pid`

differences: 

- ChrootDirectory
- AuthorizedKeysFile
- Port

**Comment by ghoneycutt** [comment]
We would need to change quite a bit. Thinking the configs would need to be defined types, so you could call them multiple times. Is it multiple ssh_config and sshd_config? Curious what your use case is that you run SSH like this. Could you elaborate?

**Comment by khaefeli** [comment]
sorry, that's a typo. I mean sshd_config_xy.

we use it as a "lightweight" file exchange with keyauth / chroot. (SFTP)
actually some ftp servers have the same functionality

**Comment by joernott** [comment]
As I am in the same situation, I have forked the module and started splitting things up. In [my fork https://github.com/joernott/puppet-module-ssh/tree/multiple_sshd_configs](https://github.com/joernott/puppet-module-ssh/tree/multiple_sshd_configs), I have moved the sshd_config handling to a defined type which is called by init. The same applies for service. This however needs some more expansion, as I want to run different services with different configs in the future. Also, package has been moved to a separate class, as someone might want to install the software and only wants to configure the sshd_config and service without managing the ssh_config.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
