### ISSUE TITLE
Hard dependency on $osfamily

### ISSUE THREAD

**Issue by darkfeline** [ghoneycutt/puppet-module-ssh#236]
This module should use something like `params.pp` or Hiera to avoid a hard dependency on `$osfamily`.

For example, if I want to use an unsupported OS like Arch Linux, I would normally be able to supply any OS-specific parameters myself even if this module does not support it natively.  However, by hard-coding the osfamily check in `init.pp`, that is not possible.

**Comment by ghoneycutt** [comment]
This module explicitly supports given platforms and chooses to fail rather than make assumptions on platform type.

I would be very happy to merge in Arch Linux support if you would like to provide it.
