### ISSUE TITLE
AuthorizedKeysCommandRunAs changed between RHEL6 and RHEL 7

### ISSUE THREAD

**Issue by evanhisey** [ghoneycutt/puppet-module-ssh#237]
The option for setting the username to run AuthorizedKeysCommand has changed between RHEL 7 and RHEL 6

AuthorizedKeysCommandUser < RHEL 7
(This Setting appears to be mandatory on RHEL7 if AuthorizedKeysCommand is used)

AuthorizedKeysCommandRunAs < RHEL 6

**Comment by Phil-Friderici** [comment]
In v4 the directive has been renamed to `AuthorizedKeysCommandUser` and support for RHEL6 has been droped.
Please re-open if this doesn't fit your use case.
