### ISSUE TITLE
Need support for X11DisplayOffset setting in sshd_config

### ISSUE THREAD

**Issue by williamkorb** [ghoneycutt/puppet-module-ssh#242]
I would like to be able to add this to my Hiera data to configure the SSH daemon:

ssh::sshd_config_x11_display_offset: '30'

...which would then set this in the sshd_config:

X11DisplayOffset 30

The default is 10, but not high enough for our environment.

The changes look rather straightforward.

In init.pp:

Add parameter with default to the ssh class:

  $sshd_config_x11_display_offset         = '10',

Add handling for undef value:

  case $sshd_config_x11_display_offset {
    'unset', undef: { $sshd_config_x11_display_offset_real = undef }
    default: { $sshd_config_x11_display_offset_real = $sshd_config_x11_display_offset_real }
  }

Add validation:

  if $sshd_config_x11_display_offset_real != undef {
    validate_integer($sshd_config_x11_display_offset_real)
  }

In sshd_config.erb add this after the current commented value of X11DisplayOffset:

<% if @sshd_config_x11_display_offset_real != nil -%>
X11DisplayOffset <%= @sshd_config_x11_display_offset_real %>
<% end -%>

Thanks for this excellent module!

I'm kind of a Puppet and GitHub n00b, but I'd be happy to do a branch and submit the changes for your consideration if that's acceptable. I've never done that before, so if you have preferences as to how that is done, please let me know.

**Comment by williamkorb** [comment]
Garrett,

I cloned your repo, created my own branch (named "addX11DisplayOffset") and incorporated my changes. Please let me know if I can become a contributor and submit my changes for your approval.

Thanks,
Bill

**Comment by williamkorb** [comment]
Garrett,

I have this change coded. Can you please grant me contributor status so that I can create a new pull request to submit my changes for review?

Thanks,
Bill

**Comment by ghoneycutt** [comment]
Anyone can submit a PR. Please do! It will need corresponding spec tests.

**Comment by williamkorb** [comment]
OK, I created a PR. Can you point me at something that will tell me how to create the spec test?

**Comment by ghoneycutt** [comment]
Check out this commit - https://github.com/ghoneycutt/puppet-module-ssh/commit/1c0d3f6bdb87aa26c21379a5230d1e10bb8f47ca

**Comment by Phil-Friderici** [comment]
Fixed in v4 branch
