### ISSUE TITLE
Doesn't support concat 3.x and 4.x

### ISSUE THREAD

**Issue by dhollinger** [ghoneycutt/puppet-module-ssh#247]
Latest version of ghoneycutt has a dependency on puppetlabs-concat, but limits the range to < 3.0.0.

We require support for puppetlabs-concat 4.x for other modules and this new restriction breaks our ability to use the latest ghoneycutt-ssh version.

Is there a reason for limiting the max concat version?

**Comment by ghoneycutt** [comment]
Good catch!

**Comment by ghoneycutt** [comment]
Released in v3.56.0
