### ISSUE TITLE
authorized_keys - Permission denied when mode = 0400. 

### ISSUE THREAD

**Issue by kkruzich** [ghoneycutt/puppet-module-ssh#254]
All of our ~/.ssh/authorized_keys were created with mode 0400 (user, read only). We want to manage these files with Puppet so I created the following: 

```
    class users {
     user { 'julia':
      home           => '/home/julia',
      ensure         => present,
      purge_ssh_keys => true,
     }
    }
    
    ssh_authorized_key { 'julia@dirty':
      ensure => present,
      user   => 'julia',
      type   => 'ssh-ed25519',
      key    => 'AAAAC3NzaC1lvvvvvvxxxxxO1mXiiyj3Af17MviiiiiiiifffffzU5e//e/ffff/y',
    }
```

However, when I run 'puppet agent --test' on a node, I get the following error: 
```

    Error: Puppet::Util::FileType::FileTypeFlat could not write /home/julia/.ssh/authorized_keys: Permission denied - /home/julia/.ssh/authorized_keys
    Error: /Stage[main]/Profile::Base/Ssh_authorized_key[julia@dirty]: Could not evaluate: Puppet::Util::FileType::FileTypeFlat could not write /home/julia/.ssh/authorized_keys: Permission denied - /home/julia/.ssh/authorized_keys
```

I am able to "patch" the issue with the following:

```
    file { "/home/julia/.ssh/authorized_keys":
        ensure => present,
        mode => '0600',
    }
```

I'm surprised this is a problem. I thought this would work with any valid mode on the file (0600 or 0400). I can't find anything in the forge module documentation about valid modes or modifying modes. The 'file' parameter is an acceptable workaround but it doesn't work as nested within the 'ssh_authorized_key' section, so not as neat as we'd like. Also, I'm not sure how to do this for many users. 

Can you offer a suggestions for handling this a better way? Is there something that could be brought into the module to modify and/or enforce a mode? 

There are a few posts via search that ask this same issue but no good solutions. Here is one from 7 years ago. I don't think the patch ever made it in the code base: https://projects.puppetlabs.com/issues/5395

**Comment by ghoneycutt** [comment]
https://puppet.com/docs/puppet/5.3/type.html#sshauthorizedkey

This only manages the contents and not the user/group/mode. I believe you will need a separate file resource as you mentioned above.
