### ISSUE TITLE
add 'AuthenticationMethods publickey,keyboard-interactive'

### ISSUE THREAD

**Issue by kkruzich** [ghoneycutt/puppet-module-ssh#261]
To accomodate third party MFA 'duo security' I need the option AuthenticationMethods to read

`AuthenticationMethods publickey,keyboard-interactive`

There's currently no way to do this with 3.56.1. Could you please add this somehow? 

As a workaround I'm doing the following (which is kind of gnarly):

```
file_line {'sshd_config_authenticationmethods':
  notify => Service['sshd'],
  path  => '/etc/ssh/sshd_config',
  line  => "AuthenticationMethods publickey,keyboard-interactive",
}
```

**Comment by ghoneycutt** [comment]
There is a parameter for that named `sshd_config_authenticationmethods`. Check out https://github.com/ghoneycutt/puppet-module-ssh#sshd_config_authenticationmethods.

```yaml
ssh::sshd_config_authenticationmethods:
  - 'publickey'
  - 'keyboard-interactive'
```

**Comment by kkruzich** [comment]
I now see this is in the most recent release here on github. However puppet forge has only 3.56.1, which doesn't include the parameter. How does the latest release become available on puppet forge?

**Comment by ghoneycutt** [comment]
@kkruzich Thanks for letting me know that the forge was behind a release!! I've updated it with v3.57.0.
