### ISSUE TITLE
migrate deprecated hiera_* to lookup() 

### ISSUE THREAD

**Issue by khaefeli** [ghoneycutt/puppet-module-ssh#263]
the `hiera_* ()` function is deprecated and should be replaced by `lookup()`.
https://docs.puppet.com/puppet/4.10/hiera_migrate_functions.html

this module is officially supporting puppet >=3.x atm.
so it's probably time to drop puppet 3.x support and migrate to 4.x, 5.x :)

**Comment by Phil-Friderici** [comment]
In v4 the hiera_merge functionality got removed entirely. You can now configure your hiera to do the merging as needed. Read more here https://www.puppet.com/docs/puppet/5.5/configure_merge_behavior_hiera.html and https://www.puppet.com/docs/puppet/7/hiera_automatic.html.
Please re-open if this doesn't fit your use case.
