### ISSUE TITLE
Messy config file

### ISSUE THREAD

**Issue by ggeldenhuis** [ghoneycutt/puppet-module-ssh#267]
Including a very basic version of class:
class { 'ssh': }

I get a /etc/ssh/sshd_config on Red Hat with loads of unnecessary comments, eg: 
```
#Port 22
Port 22
#Protocol 2,1
Protocol 2
#AddressFamily any
AddressFamily any
```
Surely you don't need  commented version of a parameter you already set? 

The config file contains a description of the "strategy" but the above is not inline with the strategy.

**Comment by Phil-Friderici** [comment]
In v4 (mostly) only the lines that got configured are added to the configuration files.
Please re-open if this doesn't fit your use case.
