### ISSUE TITLE
add id_ed25519 support

### ISSUE THREAD

**Issue by threepistons** [ghoneycutt/puppet-module-ssh#276]
Given: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips on Centos 7 and Puppet 5 and the manifest ```include ssh```
When I: try to use a pre-existing ssh ed25529 key to ssh into another server.
I get: a password prompt.
I expected: to log straight in with the private key.

Investigation shows that this module has wiped out the ssh_config entries as follows:
```
-   IdentityFile ~/.ssh/id_ecdsa
-   IdentityFile ~/.ssh/id_ed25519
```
and the sshd_config entries as follows:
```
-HostKey /etc/ssh/ssh_host_ecdsa_key
-HostKey /etc/ssh/ssh_host_ed25519_key
```
This is a nuisance because we've adopted ed25519 widely already.

Double-checking this morning, SSH with the -v option gave:
```
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
```
so ssh is definitely no longer even trying to load the id_ed25519 key.

**Comment by g2payne** [comment]
plus one to this

**Comment by anselmic** [comment]
Same problem here....

**Comment by Phil-Friderici** [comment]
Closing as v4 does offers support to flexible configure `IdentityFile` and `HostKey` with `$ssh::identity_file` and `$ssh::server::host_key`.
Please re-open if this doesn't fit your use case.
