### ISSUE TITLE
Deprecated option "useroaming"

### ISSUE THREAD

**Issue by sfuerte** [ghoneycutt/puppet-module-ssh#279]
Using 
```  
  "name": "ghoneycutt-ssh",
  "version": "3.57.1",
```
on `Debian GNU/Linux 9.5 (stretch)` with OpenSSH client & server `7.4p1-10+deb9u3`.

When doing a verbose output for SSH client, noticed the following warnings:
```
OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 50: Applying options for *
debug1: /etc/ssh/ssh_config line 57: Deprecated option "useroaming"
```

`ssh_config_use_roaming` either should be removed or be platform/version dependant.

**Comment by sfuerte** [comment]
I guess temporarily can be fixed via specifically un-setting it, e.g. (via Hiera):
`ssh::ssh_config_use_roaming: 'unset'`

but better remove its support completely.

**Comment by ghoneycutt** [comment]
We can't remove it entirely as some platforms use it, though making it platform dependent so it could be unset for Debian 9 would work.

**Comment by Phil-Friderici** [comment]
Closing as useroaming was removed from v4.
Please re-open if this doesn't fit your use case.
