### ISSUE TITLE
Puppet The string '7' was automatically coerced to the numerical value 7

### ISSUE THREAD

**Issue by linuxphone** [ghoneycutt/puppet-module-ssh#285]
Guys,
I am getting the following WARN on every node rune:

Puppet The string '7' was automatically coerced to the numerical value 7 (file: /etc/puppetlabs/code/environments/development/modules/ssh/manifests/init.pp, line: 291, column: 33)

Puppet The string '4' was automatically coerced to the numerical value 4 (file: /etc/puppetlabs/code/environments/development/modules/ssh/manifests/init.pp, line: 292, column: 32)

I am running puppet agent 5.5 and RHEL 7.5

**Comment by linuxphone** [comment]
This is the impacted lines under init.pp

    $ssh_version_maj_int = (0 + ($ssh_version_array[0]))
    $ssh_version_min_int = 0 + $ssh_version_array[1]

**Comment by ghoneycutt** [comment]
We are purposely changing the value to an integer so that we can use comparison operators on those numbers. Do you have another solution?

https://github.com/ghoneycutt/puppet-module-ssh/blob/master/manifests/init.pp#L293-L295

**Comment by linuxphone** [comment]
ghoneycutt, I am not sure on solution...are we getting a change push for this soon, if so, what would be the estimated timeframe to see this WARN gone. Please advise.

**Comment by TheMeier** [comment]
voxpupuli and puppet stdlib are starting to raise their minimum puppet requirement to <= 5.5.10. Maybe it is finally the time to ditch support for old puppet versions and use data types.

**Comment by ghoneycutt** [comment]
@TheMeier Check out PR #307 where I'm working on just that :)

**Comment by jonhattan** [comment]
Here's a fix, as seen at https://github.com/puppetlabs/puppetlabs-apt/pull/743/files
`$ssh_version_min_int = Integer($ssh_version_array[1])`

**Comment by Phil-Friderici** [comment]
Closing this as the issue is fixed in v4.
Please re-open if this doesn't fix your use case.
