### ISSUE TITLE
Puppet 6 compatibility

### ISSUE THREAD

**Issue by TheMeier** [ghoneycutt/puppet-module-ssh#290]
Puppet 6 was just released. This module is not compatible, tests result in:

```
  1) ssh with default params on osfamily Debian-7 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile.with_all_deps }
       error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'sshkey'
```

**Comment by SimonHoenscheid** [comment]
Reason is: Puppetlabs removed some core types which you can now dowload from the forge if you need them. just add it to the fixtures and it should work. 

https://forge.puppet.com/puppetlabs/sshkeys_core

**Comment by ghoneycutt** [comment]
Thanks, we need a separate fixtures file like this commit - https://github.com/sensu/sensu-puppet/commit/c0a7a2deb03a6cff304f31216a457a3dfb52b919

**Comment by binford2k** [comment]
@ghoneycutt you don't need a _separate_ fixtures file. See https://github.com/puppetlabs/puppetlabs_spec_helper/pull/258 for info.

**Comment by Phil-Friderici** [comment]
Closing as v4 is compatible with Puppet 6.
