### ISSUE TITLE
Abbility to turn off auttomatic completion of /etc/ssh/ssk_known_hosts

### ISSUE THREAD

**Issue by ggeldenhuis** [ghoneycutt/puppet-module-ssh#295]
For bigger companies 10 000+ nodes having the ssh module automatically populate /etc/ssh/ssh_know_hosts file is not great behaviour. This really should be turned of by default and a user attribute provided to turn on this behaviour. I can't currently see any flag that would allow you to easily turn off this behaviour.

**Comment by ghoneycutt** [comment]
Thanks!
