### ISSUE TITLE
How do we use this module for authorized_keys management

### ISSUE THREAD

**Issue by linuxphone** [ghoneycutt/puppet-module-ssh#299]
Dear Author,
Please provide some guidance on how to use this module for management of authorized_keys.

Keep in mind that some of us are not familiar with hiera, providing some clear details on how to accomplish this would be greatly appreciate. I am fairly familiar navigating under /etc/puppetlabs/code but I am unsure where and how we get the authorized_keys configure using this module. Your help is greatly appreciated.

**Comment by ghoneycutt** [comment]
Please check out https://github.com/ghoneycutt/puppet-module-ssh#manage-users-ssh_authorized_keys
