### ISSUE TITLE
Not working with Ubuntu 14.04 

### ISSUE THREAD

**Issue by flaporta** [ghoneycutt/puppet-module-ssh#314]
init.pp missing code to support Ubuntu14.04. The module states that 14.04 is compatible.

**Comment by witchbutter** [comment]
I had this same issue, you have to revert to 3.59.0 in order to continue working with 14.04

**Comment by efungsh** [comment]
Regression appears to have occurred when Debian 9 support was added: dce102f33ad87da6151a4d7108fd36f01c5a8e63

Default behaviour for Debian was changed from a generic set of values to a fail scenario.

Looks like following supported Ubuntu versions are affected
* Precise (12.04)
* Lucid (14.04)

**Comment by efungsh** [comment]
PR #325 lodged to resolve this

**Comment by TheMeier** [comment]
If I understand the infos on https://wiki.ubuntu.com/Releases correctly 12.04 is EOL and even Extended Security Maintenance ended in 2019

**Comment by efungsh** [comment]
Yeah, that's right.

However, this module lists it as officially supported, so the removal was inadvertent.
Restoring it was just adding back configuration defaults.

I think making a call to remove support for 12.04 LTS should be planned and it should be announced in advance.

**Comment by Phil-Friderici** [comment]
Support for Ubuntu 14.04 and 16.04 was removed.
v4 supports Ubuntu 18.04 to 20.04.
PR https://github.com/ghoneycutt/puppet-module-ssh/pull/398 will add support for 22.04.
