### ISSUE TITLE
dependency to older version of puppetlabs/concat breaks other module-installs

### ISSUE THREAD

**Issue by realvinx** [ghoneycutt/puppet-module-ssh#333]
When trying to install "puppetlabs/concat" version 6.2.0 I got the following error:
```
Notice: Preparing to install into /etc/puppetlabs/code/modules ...
Error: Could not install module 'puppetlabs-concat' (???)No version of 'puppetlabs-concat' can satisfy all dependencies
Use `puppet module install --ignore-dependencies` to install only this module
```

After some research I found that the module "ghoneycutt/ssh" has maximum version of concat 6.0.0 as dependency in its metadata.json:
```
    {"name":"puppetlabs/concat","version_requirement":">= 2.0.0 < 6.0.0"},
```

I was able to install "puppetlabs/concat" version 6.2.0 by changing the "< 6.0.0" to "< 6.3.0" in metadata.json.

But I'm wondering if this is safe to do so ?
Does "ghoneycutt/ssh" work with "puppetlabs/concat" version 6.2.0 ?
How can I be sure this has no side effects ?
There must be a reason it's limited to version 6.0.0

**Comment by Phil-Friderici** [comment]
Fixed in v4
