### ISSUE TITLE
dependency to puppetlabs-firewall < 2.0.0 breaks debian 10 compatibility

### ISSUE THREAD

**Issue by mzhaase** [ghoneycutt/puppet-module-ssh#336]
In order for this module to be Debian 10 compatible, it has to allow a higher verision of puppetlabs-firewall, since only versions starting at 2.2.0 are actually debian 10 compatible

**Comment by Wesseldr** [comment]
Is it really breaking-breaking it? 
Think I'll stick to my current ssh module and hope it gets upgraded soon :)

**Comment by Phil-Friderici** [comment]
Fixed in v4
