### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by noqqe** [ghoneycutt/puppet-module-ssh#338]
Hi,

Is this repo anyhow actively maintained?

Many PRs for current OS versions are lying around unresponded

#323 
#320 

and so on.

As this module is the most used on puppetforge and @ghoneycutt is not interested in maintaining it anymore, it may should be transfered to Voxpupuli as many others.

**Comment by ghoneycutt** [comment]
Please lend a hand in https://github.com/ghoneycutt/puppet-module-ssh/pull/307
