### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by nick-george** [ghoneycutt/puppet-module-ssh#342]
Module Version: 3.61.0

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Operating System : 20.04 not supported (file: /etc/puppetlabs/code/environments/development/modules/ssh/manifests/init.pp, line: 332, column: 20) on node testy

Thanks for your time!

**Comment by Phil-Friderici** [comment]
Ubuntu 20.04 is support in v4.
