### ISSUE TITLE
X11DisplayOffset not configurable

### ISSUE THREAD

**Issue by jim-mose** [ghoneycutt/puppet-module-ssh#350]
Hello,

Currently, the X11DisplayOffset parameter in the sshd_config template is not configurable. In a future update, would you consider adding it as a configurable parameter within your module?

Thank you,
Jim

**Comment by Phil-Friderici** [comment]
The functionality to set `X11DisplayOffset` via `$ssh::server::x11_display_offset` was added in v4.
Please re-open if this doesn't fit your use case.
