### ISSUE TITLE
Change the RekeyLimit setting

### ISSUE THREAD

**Issue by thale13** [ghoneycutt/puppet-module-ssh#353]
I have a need to change the sshd setting 'RekeyLimit'.  Is there a way to do this with the module, or does that parameter need to be added?

Looking thru the code, I don't see it anywhere.  I can change it with a file_line statement, but then I get corrective changes every run because the module removes it, then the other code I wrote adds it back in.

**Comment by Phil-Friderici** [comment]
`RekeyLimit `can be set using the `$ssh::server::rekey_limit` parameter in v4.
Please re-open if this doesn't fix your use case.
