### ISSUE TITLE
Module dependencies out of date

### ISSUE THREAD

**Issue by demonstrator** [ghoneycutt/puppet-module-ssh#378]
Hi,

Just wondering if / when this modules dependencies will be updated:

Warning: Module 'ghoneycutt-common' (v1.2.0) fails to meet some dependencies:
  'ghoneycutt-ssh' (v3.62.0) requires 'ghoneycutt-common' (>= 1.4.1 < 2.0.0)
Warning: Module 'puppetlabs-concat' (v7.0.0) fails to meet some dependencies:
  'ghoneycutt-ssh' (v3.62.0) requires 'puppetlabs-concat' (>= 2.0.0 < 7.0.0)
Warning: Module 'puppetlabs-firewall' (v3.4.0) fails to meet some dependencies:
  'ghoneycutt-ssh' (v3.62.0) requires 'puppetlabs-firewall' (>= 1.9.0 < 3.0.0)
Warning: Module 'puppetlabs-stdlib' (v7.1.0) fails to meet some dependencies:
  'ghoneycutt-ssh' (v3.62.0) requires 'puppetlabs-stdlib' (>= 4.6.0 < 7.0.0)
/etc/puppetlabs/code/environments/production/modules
└── puppet-systemd (v3.8.0)
/etc/puppetlabs/code/environments/common
├── ghoneycutt-common (v1.2.0)  invalid
├── ghoneycutt-ssh (v3.62.0)
├── puppet-chrony (v2.3.0)
├── puppetlabs-apt (v8.3.0)
├── puppetlabs-concat (v7.0.0)  invalid
├── puppetlabs-firewall (v3.4.0)  invalid
├── puppetlabs-inifile (v5.2.0)
├── puppetlabs-motd (v6.1.0)
├── puppetlabs-postgresql (v7.5.0)
├── puppetlabs-puppetdb (v7.10.0)
├── puppetlabs-registry (v4.0.1)
├── puppetlabs-sshkeys_core (v2.3.0)
├── puppetlabs-stdlib (v7.1.0)  invalid
├── puppetlabs-translate (v2.2.0)
└── ssm-munin (v0.1.0)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
/usr/share/puppet/modules (no modules installed)

Thanks

V

**Comment by demonstrator** [comment]
Is this module still being maintained? I'll choose another module if this one isn't going to be updated going forward. Please let me know as soon as you can. Thanks.

**Comment by chhex** [comment]
It is a great module, but  because of the wrong dependency resolution, one has to manually edit Puppetfile under bolt.

**Comment by canihavethisone** [comment]
Bump to please republish with updated dependencies, including stdlib v8.  Thank you.

**Comment by Phil-Friderici** [comment]
Fixed in v4
