### ISSUE TITLE
Add support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by threepistons** [ghoneycutt/puppet-module-ssh#380]
In branches v4 and master, there is no support listed in metadata.json for Ubuntu 22.04 LTS

**Comment by baron1405** [comment]
Is there an ETA for 22.04 support?

**Comment by baron1405** [comment]
@ghoneycutt Apparently PR #377 is available for merging to support Ubuntu 22.04

**Comment by baron1405** [comment]
@ghoneycutt Is this module still supported?

**Comment by absld** [comment]
@ghoneycutt It would be great, if you could take a look on #377 in the next days

**Comment by blodone** [comment]
+1

**Comment by Phil-Friderici** [comment]
Support for Ubuntu 22.04 will be added with PR https://github.com/ghoneycutt/puppet-module-ssh/pull/398.

**Comment by Phil-Friderici** [comment]
@baron1405 waiting for the owner to review and merge it.
Keeping my fingers crossed that @treydock will have some time soon :)

**Comment by ghoneycutt** [comment]
Thank you for your contributions and help! This is merged in https://github.com/ghoneycutt/puppet-module-ssh/pull/402 and released in `4.1.0`.

**Comment by baron1405** [comment]
Thanks to all who participated!
