### ISSUE TITLE
config_mode not documented in version 4 of UPGRADING.md

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-ssh#382]
The old parameter, ssh_config_mode has been renamed to config_mode yet it's not documented in the UPGRADING.md file.  Since this is neither a client nor a server setting (it's the file mode of /etc/ssh/sshd_config and other files) I'm unsure where the correct place to document this change is.

**Comment by ghoneycutt** [comment]
sshd is the server and ssh is the client. Closing this as most users will never touch this as changing the mode is not common practice and can keep ssh from functioning.
