### ISSUE TITLE
V4 - ChallengeResponseAuthentication has wrong (new) variable name.

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-ssh#383]
In [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/v4/UPGRADING.md) the ChallengeResponseAuthentication setting points to 'kbd_interactive_authentication' for version 4 of the module.  Should this be something more like "challenge_resp_auth" in keeping with the other upgraded variables?

ChallengeResponseAuthentication is a deprecated option for RHEL9 but not for RHEL8 and older.

**Comment by Phil-Friderici** [comment]
The parameter was renamed from `ChallengeResponseAuthentication` to `KbdInteractiveAuthentication` [1]. If you need to use the old name you can still use `$custom` to set it to your needs.

[1] https://man.openbsd.org/ssh_config#KbdInteractiveAuthentication

**Comment by Phil-Friderici** [comment]
Closing as the needed functionality is able to reached with the `$custom` parameter in v4.
