### ISSUE TITLE
Feature request: Allow multiple instances of sshd

### ISSUE THREAD

**Issue by GertjanBijl** [ghoneycutt/puppet-module-ssh#387]
Looking into the code, it seems to be impossible to run multiple instances of sshd without cloning the repository and change the class-name. Since we run multiple ssh-instances on a single host, for example one for management and one for just SFTP, or on another machine: one with 2FA enabled for external connections and one without 2FA for internal connections, it would be really nice to be able to do that using a defined class.

Are more people in need of this, or are we the odd one out?

**Comment by ghoneycutt** [comment]
We are not interested in supporting running multiple instances of a service with this module. This is a common stance with modules. You could use this module along with the new ssh.d include functionality (https://github.com/ghoneycutt/puppet-module-ssh#manage-configurations-files-in-d-directories) to manage multiple ssh configurations and then wrap this in a profile that manages your custom services (ie: your special service directives for managing the extra ssh services).
