### ISSUE TITLE
Add hiera support for Oracle Linux 8

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-ssh#388]
./data/os/OracleLinux/8.yaml needs to be created.  I copied 7.yaml to 8.yaml and tested it successfully against all of my Oracle Linux 8 servers.

**Comment by demonstrator** [comment]
I think this module has been abandoned I'm afraid.

**Comment by bschonec** [comment]
That's unfortunate as ghoneycutt has been a big contributor to the Puppet world.  Do you have any recommendations for an alternative module for SSH management?

**Comment by Phil-Friderici** [comment]
Support for Oracle Linux 8 will be added with PR https://github.com/ghoneycutt/puppet-module-ssh/pull/398.
