### ISSUE TITLE
ssh_key_import not included in v4

### ISSUE THREAD

**Issue by darktim** [ghoneycutt/puppet-module-ssh#392]
Hi,

the functionality of exporting host_keys and importing them on other servers is not included any more in v4.

May I ask why this feature has been discarded?

Greetz,
Andre

**Comment by anders-larsson** [comment]
FYI @Phil-Friderici.

Has the situation improved with exporting/import ssh host keys? I know previously it worked horribly and caused a lot of issues at least in our environment. It wasn't a week without errors caused by this functionality due to different issues like duplicate entries etc.

**Comment by fuerer** [comment]
we used that feature and it worked quite well. Any chance this is coming back in a future version?

**Comment by gss2002** [comment]
It can be done with the following add it in another class and it will add the known host entries:
class profile::hadoop::hadoop_sshconfig (
  $ssh_key_import = true,
  $ssh_key_type  = 'ssh-rsa',
  $ssh_key_ensure = 'present',
  $ssh_config_global_known_hosts_file         = '/etc/ssh/ssh_known_hosts',
){


  case $ssh_key_type {
    'ssh-rsa','rsa': {
      $key = $::sshrsakey
    }
    'ssh-dsa','dsa': {
      $key = $::sshdsakey
    }
    'ecdsa-sha2-nistp256': {
          $key = $::sshecdsakey
    }
    default: {
      fail("ssh::ssh_key_type must be 'ecdsa-sha2-nistp256', 'ssh-rsa', 'rsa', 'ssh-dsa', or 'dsa' and is <${ssh_key_type}>.")
    }
  }

  if getvar('::ipaddress') and getvar('::ipaddress6') {
      $host_aliases = [$::hostname, $::ipaddress, $::ipaddress6]
  } elsif getvar('::ipaddress6') {
      $host_aliases = [$::hostname, $::ipaddress6]
  } else {
    $host_aliases = [$::hostname, $::ipaddress]
  }

  # export each node's ssh key
  @@sshkey { $::fqdn :
    ensure       => $ssh_key_ensure,
    host_aliases => $host_aliases,
    type         => $ssh_key_type,
    key          => $key,
  }

  # import all nodes' ssh keys
  if $ssh_key_import == true {
    Sshkey <<||>> {
      target => $ssh_config_global_known_hosts_file,
    }
  }
}

**Comment by gss2002** [comment]
Here is a sample that makes it work again just create a class and toss the attached in... This did work quite well... 
[hadoop_sshconfig.txt](https://github.com/ghoneycutt/puppet-module-ssh/files/10515346/hadoop_sshconfig.txt)

**Comment by fuerer** [comment]
thx gss2002, it is working fine again

**Comment by WembleyFord2** [comment]
That's a nice workround gss2002 - but it would be good too know if this functionality is perminantly removed from the module, or may appear in future revisions of version 4.  There's nothing in the changelog or upgrade notes I could spot concerning this.

**Comment by ghoneycutt** [comment]
We are no longer supporting exported resources. You can implement this in a profile though.
