### ISSUE TITLE
where is the hiera_merge feature in new version?

### ISSUE THREAD

**Issue by taleintervenor** [ghoneycutt/puppet-module-ssh#393]
In version 3.* there is hiera_merge argument to let user define global-wide ssh key along with additional key only on some specific nodes. And in old doc it is wrote:

```
hiera_merge
Boolean to merges all found instances of ssh::keys and ssh::config_entries in Hiera. This is useful for specifying SSH keys at different levels of the hierarchy and having them all included in the catalog.

This will default to 'true' in future versions.
```

But I can't find the merge action in current version. Is this feature be forgotten?

**Comment by anders-larsson** [comment]
Hi,

In newer version of hiera you can do the merging in Hiera itself and I suspect that was why the functionality was removed from the module itself.

Read more here https://www.puppet.com/docs/puppet/5.5/configure_merge_behavior_hiera.html.
