### ISSUE TITLE
V4: wrong IdentityFile line in ssh_config

### ISSUE THREAD

**Issue by nowack73** [ghoneycutt/puppet-module-ssh#399]
If one configures multiple identity files, the resulting ssh_config contains only one line with `IdentityFile` mixing all file names into one long file name.

Hiera data:
```
ssh::pruge_keys: true
ssh::identity_file:
  - ~/.ssh/id_rsa
  - ~/.ssh/id_ecdsa
  - ~/.ssh/id_ed25519
```

The result in /etc/ssh_config is:
```
IdentityFile ~/.ssh/id_rsa,~/.ssh/id_ecdsa,~/.ssh/id_ed25519
```

But it should be:
```
IdentityFile ~/.ssh/id_rsa
IdentityFile ~/.ssh/id_ecdsa
IdentityFile ~/.ssh/id_ed25519
```

**Comment by Phil-Friderici** [comment]
Created #404 which will create one HostCertificate line for each file.
