### ISSUE TITLE
identityfile doesn't work right.

### ISSUE THREAD

**Issue by timeweaver** [ghoneycutt/puppet-module-ssh#422]
We attempted to set multiple identity_files in an array like this:
`ssh::identity_file:`
`  - '~/.ssh/id_rsa'`
`   - '~/.ssh/id_dsa' `

  
  But that resulted in a comma delimited entry
  `  IdentityFile ~/.ssh/id_rsa, ~/.ssh/id_dsa`
  
  Instead of multiple lines like this:
`  IdentityFile ~/.ssh/id_rsa`
`  IdentityFile ~/.ssh/id_rsa`

**Comment by ghoneycutt** [comment]
Perhaps you were using an older version? The template does not join the array with commas so this is not possible.
