### ISSUE TITLE
UseRoaming client parameter does not respect the $use_roaming parameter

### ISSUE THREAD

**Issue by glangloi** [ghoneycutt/puppet-module-ssh#423]
The ssh class accepts the $use_roaming parameter, but it appears that it is unused in the client config template.

As a workaround, we can use $custom to configure UseRoaming.

**Comment by ghoneycutt** [comment]
Thank you for using this module and pointing that out. This is due to an major version change where we went from ad-hoc support of SSH options to supporting every option available in the man pages and more. Notes are in https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md
