### ISSUE TITLE
re-integrate Ubuntu 18.04 support

### ISSUE THREAD

**Issue by mabe443** [ghoneycutt/puppet-module-ssh#424]
I have seen, that in the PR #417 the support for `Ubuntu 18.04 LTS` was dropped in this module.

Since many companies still use  `Ubuntu 18.04 LTS` with [Expanded Security Maintenance (ESM)](https://ubuntu.com/security/esm), which is extending the support until 2028 I am kindly asking if it would be possible to bring back the support for Ubuntu 18.04 with this ssh module.

Or are there any dependencies that prevent my request?

**Comment by ghoneycutt** [comment]
Hi, thank you for using this module. It is designed to be totally extendable through Hiera. While we will not officially support this EOL version, you can just add the Hiera data that was removed in the PR above and it will continue to work.
