### ISSUE TITLE
cannot specify a `Host` setting with a wildcard for `ssh::ssh_config`

### ISSUE THREAD

**Issue by bwitt** [ghoneycutt/puppet-module-ssh#425]
I can't seem to add a `Host` entry for `ssh::ssh_config` that has a wildcard.

That seems to be because [that entry is required to be a stdlib::host](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/REFERENCE.md#sshssh_config) ([stdlib::host docs here](https://github.com/puppetlabs/puppetlabs-stdlib#stdlibhost)) which can only be an ip address, fqdn, or short hostname.

The SSH client accepts things that have a wildcard; could the module accept that here?  could this just be a String?

**Comment by ghoneycutt** [comment]
`Stdlib::Host` allows for short names. Could you provide the name you are attempting?

**Comment by bwitt** [comment]
sorry I actually meant a Host entry with a wildcard like this does not work
```
Host: *.example.com
ForwardAgent: 'yes'
```

a Host entry with just a shortname does seem to work.

**Comment by ghoneycutt** [comment]
The documentation you linked is incorrect. The code does a `String` match and not `Stdlib::Host`.

**Comment by ghoneycutt** [comment]
Fix is in v5.1.1
