### ISSUE TITLE
Multiple lines with same directive name - how to specify as Lines in included file ?

### ISSUE THREAD

**Issue by iscb1962** [ghoneycutt/puppet-module-ssh#429]
Hi

Trying to add multiple SendEnv lines to a config file using something like

ssh::config_files:
  '50-redhat':
    lines:
     SendEnv: LANG
     SendEnv: LC_TIME
this result in just the last entry being included in the file

Using
    lines:
     SendEnv:
        - LANG
        - LC_TIME
Gets "Error while evaluating a Resource Statement, Ssh::Config_file_client[50-redhat]: parameter 'lines' entry 'SendEnv' expects a String value, got Tuple"

Using
    custom:
       - 'SendEnv LANG'
       - 'SendEnv LC_TIME'

Works - as you would expect (as its just copied to the file) - just misses out on the validation.

**Comment by ghoneycutt** [comment]
Thanks for posting this. `lines` must be a hash and in the first example you have duplicate names for the keys which is why you just see one entry. Glad you were able to work around with `custom`.
