### ISSUE TITLE
package class ssh_packages issue in puppet >=v3.4

### ISSUE THREAD

**Issue by avishaym** [ghoneycutt/puppet-module-ssh#46]
According to this issue : https://projects.puppetlabs.com/issues/22557
Regression on arrays and puppet resources using the name attribute will not be possible any more.

this results with the error:
Error: Failed to apply catalog: Parameter name failed on Package[ssh_packages]: Name must be a String not Array at /etc/puppet/environments/X/modules/ssh/manifests/init.pp:XXX
Wrapped exception:
Name must be a String not Array

**Comment by ghoneycutt** [comment]
This has been solved by this module for quite awhile.
