### ISSUE TITLE
ClientAliveInterval doesn't have to be an integer could be validated as a string

### ISSUE THREAD

**Issue by mlehner616** [ghoneycutt/puppet-module-ssh#58]
This is somewhat cosmetic but clientAliveInterval (possibly others) should be validated as a string (perhaps with a regex) instead of an integer. I can work up a pull request but I wanted to see what your thoughts were. For example, the following is perfectly valid: 

```
ClientAliveInterval 10m
```

which is functionally equivalent to:

```
ClientAliveInterval 600
```

**Comment by ghoneycutt** [comment]
Cleaning out old issues. If you are still interested in this, I would be happy to accept a PR.
